version: "3.9"
services:
  mcp_server:
    build:
      context: .
      dockerfile: mcp_server/Dockerfile
    container_name: mcp_server
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - finagent_net

  agent:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: langgraph_agent
    depends_on:
      - mcp_server
    env_file:
      - .env
    networks:
      - finagent_net

networks:
  finagent_net:
    driver: bridge